import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/shared/header/Header";
import Navbar from "./components/shared/navbar/Navbar";
import SidebarForUpperThanSm from "./components/shared/sidbarForUpperThanSm/SidebarForUpperThanSm";
import Title from "./components/ui(reusable)/Title";
import MenuForSm from "./components/shared/menuForSmScreen/MenuForSm";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // data-theme="light"
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <>
          <Header />
          <Navbar />
          <div>
            <Title
              className={"text-3xl font-semibold text-white ml-[90px] my-5 hidden md:block"}
            >
              Lorem, ipsum.
            </Title>

            {/* thisComponetSidbarWasRendarForTheMd/Lg/XlScreen */}
            <SidebarForUpperThanSm />

            {/* thisComponentWasRendarTheMenuItemsForSmScreen */}
            {/* <MenuForSm/> */}
          </div>
          {children}
        </>
      </body>
    </html>
  );
}
